wipe;
source DynSettings.tcl;
model BasicBuilder -ndm 2 -ndf 3;
set story ;
node 0 0 0;
fix 0 1 1 1;
set mass {};
set s1p {};
set e1p {};
set s2p {};
set e2p {};
set s3p {};
set e3p {};
set s1n {};
set e1n {};
set s2n {};
set e2n {};
set s3n {};
set e3n {};
set pinchX {};
set pinchY {};
set damage1 {};
set damage2 {};
set beta {};
set height {};
for {set i 0} {$i < $story} {incr i} {
  node [expr $i + 1] 0 [lindex $height $i];
  mass [expr $i + 1] [lindex $mass $i] 0 0;
  fix [expr $i + 1] 0 1 1;
  uniaxialMaterial Hysteretic [expr $i + 1] [lindex $s1p $i] [lindex $e1p $i] [lindex $s2p $i] [lindex $e2p $i] [lindex $s3p $i] [lindex $e3p $i] \
                                            [lindex $s1n $i] [lindex $e1n $i] [lindex $s2n $i] [lindex $e2n $i] [lindex $s3n $i] [lindex $e3n $i] \
                                            [lindex $pinchX $i] [lindex $pinchY $i] [lindex $damage1 $i] [lindex $damage2 $i] [lindex $beta $i];
  element twoNodeLink [expr $i + 1] $i [expr $i + 1] -mat [expr $i + 1] [expr $i + 1] [expr $i + 1] -dir 1 2 3;
};
set xDamp 0.05;
set nEigenI 1;
set nEigenJ 2;
set lambdaN [eigen -fullGenLapack [expr $nEigenJ]];
set lambdaI [lindex $lambdaN [expr $nEigenI - 1]];
set lambdaJ [lindex $lambdaN [expr $nEigenJ - 1]];
set omegaI [expr pow($lambdaI, 0.5)];
set omegaJ [expr pow($lambdaJ, 0.5)];
set alphaM [expr $xDamp * (2 * $omegaI * $omegaJ) / ($omegaI + $omegaJ)];
set betaKcurr [expr 2. * $xDamp / ($omegaI + $omegaJ)];
rayleigh $alphaM $betaKcurr 0 0;
timeSeries Path 2 -dt $dt -filePath $path_GMR -factor $factor;
pattern UniformExcitation 2 1 -accel 2;
file mkdir $dataDir;
for {set i 0} {$i < $story} {incr i} {
  recorder Node -file $dataDir/Dyn_[expr $i + 1]_disp.out -time -node [expr $i + 1] -dof 1 disp;
  recorder Node -file $dataDir/Dyn_[expr $i + 1]_vel.out -time -node [expr $i + 1] -dof 1 vel;
  recorder Node -file $dataDir/Dyn_[expr $i + 1]_accel.out -timeSeries 2 -time -node [expr $i + 1] -dof 1 accel;
};
constraints Transformation;
numberer Plain;
system BandGeneral;
integrator Newmark 0.5 0.25;
source SmartAnalyze.tcl;
SmartAnalyzeTransient $dt $npts;
